### ISSUE TITLE
What's the email and password?

### ISSUE THREAD

**Issue by vm10k** [webwhiz-ai/webwhiz#147] opened 2024-01-30 22:09 UTC
Hello there
I was trying to make it with docker and after finishing the installation i gone to localhost
It opened up a sign up page tried to enter anything it didn't let me so how to access it?
![IMG_20240130_235931](https://github.com/webwhiz-ai/webwhiz/assets/129557697/cce09acb-14ba-4496-a741-087ba8967000)

**Comment by hrithikt** [comment] 2024-01-31 07:26
Hi @vm10k 
Can you share more details about the error you are getting. What is the error response you are getting from the API when you are signing up. Also could you check for any errors that are getting printed in the console of nest app.

**Comment by hrithikt** [comment] 2024-02-01 05:10
> ![unknown_2024 01 31-19 21_1](https://private-user-images.githubusercontent.com/129557697/301250362-b6cf2489-5679-4d7b-8ff4-a0074198e81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjQyMDIsIm5iZiI6MTcwNjc2MzkwMiwicGF0aCI6Ii8xMjk1NTc2OTcvMzAxMjUwMzYyLWI2Y2YyNDg5LTU2NzktNGQ3Yi04ZmY0LWEwMDc0MTk4ZTgxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwNTA1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzUzNmQ0YjE4N2U5ZjdkYmQwOGYwZGQ3NGVkNjcyY2NhZTAyNjY4M2Y4NTMyMjgyZGQxZDIyYjhjY2Q5NmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vunz_h2UVCdpktBBwY3f43wuXBIpA0p0fsjgIZztXpI)

A fix has been committed for this issue yesterday [ commit 10113839899a207ac2e9117565673a76fe062118]. could you pull the new changes and try again. If possible Please confirm that the issue is fixed and signup flow with email and password is working now.

**Comment by hrithikt** [comment] 2024-02-01 05:16
> now every time i'm making a new open ai key github alerting openai and open ai deletes it , any idea how to fix that ? i cant make the repo private to avoid destroying the key

I'm curious to understand the reason behind committing the api-key to GitHub. It's not secure to commit API keys to a public repository.

**Comment by hrithikt** [comment] 2024-02-01 11:27
> > > now every time i'm making a new open ai key github alerting openai and open ai deletes it , any idea how to fix that ? i cant make the repo private to avoid destroying the key
> > 
> > 
> > I'm curious to understand the reason behind committing the api-key to GitHub. It's not secure to commit API keys to a public repository.
> 
> There's no other way to use open ai key in public repo it has to be private in order to use it If we can add it manually from your system it would be working fine to put it via the settings but i tried it , didn't work yesterday

You only need to add the key in your local repo. There is not need to commit the key and push it to the remote repo.

**Comment by hrithikt** [comment] 2024-02-02 05:03
> Sorry but how to put the key on local repo? Could show me with screenshot I'm lost since yesterday
you can add the key to the .env.docker file in your local checkout of the repository and try. Don't commit and push that change into github.

**Closed as completed** 2024-02-03 08:03 UTC
